// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type UserInfoRequest struct {
	Id int64 `path:"id"`
}

type UserInfoResponse struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Age  int32  `json:"age"`
}
