global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
  - name: webhook_receiver
    webhook_configs:
      - url: 'https://webhook.site/2546234f-5f56-4ccf-ab2c-d174c17fca43'
        send_resolved: false